### ISSUE TITLE
deploy.config.js里面的script要和package.json的对应

### ISSUE THREAD

**Issue by taosiqi** [fuchengwei/deploy-cli-service#13]
如题 不然打包就回出错

**Comment by ZhongHongLi** [comment]
我的package.json 里面是 scripts 跟那边对应的是一样的也报错呢

**Comment by fuchengwei** [comment]
> 我的package.json 里面是 scripts 跟那边对应的是一样的也报错呢

肯定是不对应的或者目录层级有问题

**Comment by ZhongHongLi** [comment]
哦哦，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fuchengwei"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 下午2:20
收件人: "fuchengwei/deploy-cli-service"<deploy-cli-service@noreply.github.com&gt;; 
抄送: "遗忘的小丑"<www.fz948605929@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [fuchengwei/deploy-cli-service] deploy.config.js里面的script要和package.json的对应 (#13)





  
我的package.json 里面是 scripts 跟那边对应的是一样的也报错呢
  
肯定是不对应的或者目录层级有问题
