### ISSUE TITLE
是否需要一个后置任务，用于检测是否复制成功

### ISSUE THREAD

**Issue by cn1001wang** [fuchengwei/deploy-cli-service#14]
我早上用的时候，不知道为什么我的.zip文件复制到测试环境中, 但没进行解压。最后控制台得到的解压成功，更新成功。（这个时候是已经有unzip命令的）
（我发现我windows Server一开始没有unzip命令的时候，ssh.execCommand也不会报错）。
但我想再复现都没复现出来。

所以
1.让他报错报出来（这个不知道ssh.execCommand能不能支持），
2.加一个后置任务，我自己加一段代码支持用来检测 这个页面能不能正常访问

**Comment by fuchengwei** [comment]
ssh.execCommand 无法知道这个命令是否执行成功

**Comment by duanxingyu** [comment]
> 我早上用的时候，不知道为什么我的.zip文件复制到测试环境中, 但没进行解压。最后控制台得到的解压成功，更新成功。（这个时候是已经有unzip命令的）
> （我发现我windows Server一开始没有unzip命令的时候，ssh.execCommand也不会报错）。
> 但我想再复现都没复现出来。
> 
> 所以
> 1.让他报错报出来（这个不知道ssh.execCommand能不能支持），
> 2.加一个后置任务，我自己加一段代码支持用来检测 这个页面能不能正常访问
你这个问题解决了吗？Windows server unzip无法解压问题

**Comment by wosdadawdawdsdw** [comment]
前辈你好，我是小白，我也遇到了上述没有解压的问题，请问有什么可以解决的办法吗

**Comment by fuchengwei** [comment]
> 前辈你好，我是小白，我也遇到了上述没有解压的问题，请问有什么可以解决的办法吗

你的 windows 服务器上装 unzip 了吗
