### ISSUE TITLE
建议增加服务器远程备份功能

### ISSUE THREAD

**Issue by wkl007** [fuchengwei/deploy-cli-service#18]
[https://github.com/aotianwinter/my-auto-deploy](url)类似这个项目中的功能
![image-20201009091435397](https://pic-go-1256738511.cos.ap-chengdu.myqcloud.com/images/20201009091444.png)

**Comment by fuchengwei** [comment]
谢谢你的建议 我会参考的

**Comment by xcsweb** [comment]
或者弄个有效期，服务端最多保存几个版本

**Comment by fuchengwei** [comment]
最新版本已经增加这个功能
