### ISSUE TITLE
等待握手时超时

### ISSUE THREAD

**Issue by ankeji** [fuchengwei/deploy-cli-service#19]
![image](https://user-images.githubusercontent.com/48073752/95736403-c5fadd00-0cb8-11eb-8f0a-304d66051be8.png)

**Comment by fuchengwei** [comment]
你的服务器是否支持 ssh 连接

**Comment by ankeji** [comment]
支持的，我刚链接过

发自我的iPhone

**Comment by fuchengwei** [comment]
连接账号的权限有检查过吗
