### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by senbochen** [fuchengwei/deploy-cli-service#2]
![image](https://user-images.githubusercontent.com/45449695/93311881-1ce7d080-f839-11ea-91c5-15dc6b1c4b22.png)
这是啥原因造成的

**Comment by fuchengwei** [comment]
看样子 应该是你服务器连接超时 连接不上服务器的问题 你检查下 ip 用户名 密码配置是否正确 在本地 ssh 连接看能连接上服务器吗？本地要是可以连接上 这个工具也是没问题的
