### ISSUE TITLE
希望增加一个配置项

### ISSUE THREAD

**Issue by 25juan** [fuchengwei/deploy-cli-service#20]
希望增加一个配置项来配置 文件打包上传成功之后是否要删除上传到服务器的.zip文件。因为我们部署到测试环境之后 确认了没问题就直接拷贝测试服务器的.zip文件到正式服务器运行即可。
谢谢

**Comment by fuchengwei** [comment]
不是应该部署测试环境没有问题后，执行部署生产环境吗？这样应该比较合理一些

**Comment by 25juan** [comment]
对了，可以这么做。但是我们这边的流程是运维只能拷贝测试服务器的测试没问题的项目到正式环境。运维拷贝过去之后只需要改一下前端访问后端的api请求接口地址就可以了。前端是被禁止了直接访问正式服务器的。测试服务器是可以随便整的

**Comment by fuchengwei** [comment]
那这个我可以增加一个配置项 配置项默认是删除的

**Comment by 25juan** [comment]
对的 是这个意思。谢谢

**Comment by duanxingyu** [comment]
windows server 上传成功后，无法解压也无法删除旧文件，unzip也安装了，也配置了环境变量

**Comment by fuchengwei** [comment]
> windows server 上传成功后，无法解压也无法删除旧文件，unzip也安装了，也配置了环境变量

试试在windonws server 上手动使用unzip命令解压试试看可以吗

**Comment by CLiangs** [comment]
看现在的代码默认解压完后就会删除上传到服务器的.zip文件了，没有加配置项吗？
<img width="763" alt="image" src="https://user-images.githubusercontent.com/24502999/217732373-af066eed-c5c3-40fe-9d20-449dd2533fb6.png">
