### ISSUE TITLE
deploy-cli-service 全局安装，有时候打不了包

### ISSUE THREAD

**Issue by xcsweb** [fuchengwei/deploy-cli-service#24]
![](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/dcbf91ce15cd415d814b9cce50fe2fab~tplv-k3u1fbpfcp-watermark.image)
全局安装的时候，经常卡在正在打包这里
npm link 把全局的包放到项目中后又可以打包了

**Comment by fuchengwei** [comment]
有明确的触发原因吗

**Comment by xcsweb** [comment]
就是没有找到问题，单独打包能打包，但是用这个打包经常会卡在打包那里

**Comment by fuchengwei** [comment]
应该和node的缓冲区大小有关系 这个后面我改成可配置的吧
