### ISSUE TITLE
求助!一直再loading.... 正在打包中。。。

### ISSUE THREAD

**Issue by zss1004504439** [fuchengwei/deploy-cli-service#25]
![image](https://user-images.githubusercontent.com/24915880/98510155-8e725700-229d-11eb-9cfb-06177cbb8a08.png)
用的 root 和 密码；privateKey和passphrase为空

**Comment by fuchengwei** [comment]
你单独运行 npm run build:preview 命令打包正常吗？需要多久？

**Comment by zss1004504439** [comment]
> 你单独运行 npm run build:preview 命令打包正常吗？需要多久？

一分钟左右

**Comment by fuchengwei** [comment]
应该不存在卡主的情况 这个只不过是在后台执行 npm run build:preview 你再试试 看看有没有什么报错

**Comment by zss1004504439** [comment]
> 应该不存在卡主的情况 这个只不过是在后台执行 npm run build:preview 你再试试 看看有没有什么报错

用的root账户 服务器需要什么开放什么权限吗

**Comment by zss1004504439** [comment]
> 应该不存在卡主的情况 这个只不过是在后台执行 npm run build:preview 你再试试 看看有没有什么报错

```deploy.config.js
module.exports = {
  projectName: 'xxx',
  privateKey: '',
  passphrase: '',
  cluster: [],
  test: {
    name: '测试环境',
    script: 'npm run build:preview',
    host: 'xx.xx.xxx.xxx',
    port: 22,
    username: 'root',
    password: 'xxxxxx',
    distPath: 'dist',
    webDir: '/usr/local/nginx/html',
    isRemoveRemoteFile: false
  },
  prod: {
    name: '生产环境',
    script: 'npm run build:prod',
    host: '',
    port: 22,
    username: 'root',
    password: '',
    distPath: 'dist',
    webDir: '',
    isRemoveRemoteFile: true
  }
}

```

**Comment by fuchengwei** [comment]
> > 应该不存在卡主的情况 这个只不过是在后台执行 npm run build:preview 你再试试 看看有没有什么报错
> 
> 用的root账户 服务器需要什么开放什么权限吗

不需要什么权限

**Comment by fuchengwei** [comment]
> > 应该不存在卡主的情况 这个只不过是在后台执行 npm run build:preview 你再试试 看看有没有什么报错
> 
> ```js
> module.exports = {
>   projectName: 'xxx',
>   privateKey: '',
>   passphrase: '',
>   cluster: [],
>   test: {
>     name: '测试环境',
>     script: 'npm run build:preview',
>     host: 'xx.xx.xxx.xxx',
>     port: 22,
>     username: 'root',
>     password: 'xxxxxx',
>     distPath: 'dist',
>     webDir: '/usr/local/nginx/html',
>     isRemoveRemoteFile: false
>   },
>   prod: {
>     name: '生产环境',
>     script: 'npm run build:prod',
>     host: '',
>     port: 22,
>     username: 'root',
>     password: '',
>     distPath: 'dist',
>     webDir: '',
>     isRemoveRemoteFile: true
>   }
> }
> ```
你 package.json 文件中也写的 npm run build:preview ？

**Comment by zss1004504439** [comment]
![image](https://user-images.githubusercontent.com/24915880/98528327-1add4380-22b7-11eb-999a-2f77861a69e1.png)
