### ISSUE TITLE
打包成功了 服务器为什么没解压

### ISSUE THREAD

**Issue by zss1004504439** [fuchengwei/deploy-cli-service#26]
![image](https://user-images.githubusercontent.com/24915880/98614101-b6f86080-2332-11eb-8755-22774291ea3b.png)
服务器
![image](https://user-images.githubusercontent.com/24915880/98614159-d099a800-2332-11eb-9cd6-3f946869e8ad.png)

**Comment by fuchengwei** [comment]
看下你 服务器是否没有安装 unzip 没有的话 yum install unzip 一下
