### ISSUE TITLE
希望能支持动静分离

### ISSUE THREAD

**Issue by guohui666** [fuchengwei/deploy-cli-service#27]
目前公司正式环境是将index.html放到服务器，其他静态文件全部放到阿里oss，要是能支持index传服务器，其他文件传oss就好了

**Comment by fuchengwei** [comment]
你可以把正式环境的 distPath 配置为 dist/static 就可以了

**Comment by guohui666** [comment]
这不就反了嘛？是想要将static 传oss上，能集成ossutil那就完美了，使用ossutil上传static到oss， 单独将index.html传到自己的服务器

**Comment by guohui666** [comment]
@fuchengwei 而且发现个问题，打包上传后修改时间对不上
![image](https://user-images.githubusercontent.com/32350854/99754460-61d30080-2b23-11eb-87d0-de55fa969a49.png)
实际上我是11.27发布的，修改时间往后倒退了8个小时，是时区的问题吗？

**Comment by fuchengwei** [comment]
> @fuchengwei 而且发现个问题，打包上传后修改时间对不上
> ![image](https://user-images.githubusercontent.com/32350854/99754460-61d30080-2b23-11eb-87d0-de55fa969a49.png)
> 实际上我是11.27发布的，修改时间往后倒退了8个小时，是时区的问题吗？

这应该是你的服务器时区的问题

**Comment by fuchengwei** [comment]
> 这不就反了嘛？是想要将static 传oss上，能集成ossutil那就完美了，使用ossutil上传static到oss， 单独将index.html传到自己的服务器

oss 的目前支持不了 单独传 index.html 倒是可以
