### ISSUE TITLE
配置文件中删除 script 字段报错

### ISSUE THREAD

**Issue by xiaosan666** [fuchengwei/deploy-cli-service#28]
配置文件中删除 script 字段报错。提示“× 配置错误: test环境 script属性 配置不正确”

**Comment by fuchengwei** [comment]
这个字段是必填项 打包运行的命令

**Comment by xiaosan666** [comment]
@fuchengwei 文档说不是必填，可以删除；
![image](https://user-images.githubusercontent.com/8148364/100820642-9468eb80-3489-11eb-813e-bf3f3af90246.png)

**Comment by fuchengwei** [comment]
这里是我疏忽验证这里的忘记去掉了 你更新最新版本 v1.2.3试试

**Comment by xiaosan666** [comment]
感谢！升级到v1.2.3确实可以了。有个额外需求，希望能支持 https://github.com/fuchengwei/deploy-cli-service/issues/29#issue-755008965
