### ISSUE TITLE
希望增加配置，不删除打包目录

### ISSUE THREAD

**Issue by xiaosan666** [fuchengwei/deploy-cli-service#29]
项目下有个docs目录写的是项目文档，文档也是部署到nginx，当前执行发布命令后把会把docs目录删掉，希望增加配置可以不删除；也可以理解发布成功后，不删除dist文件夹
![image](https://user-images.githubusercontent.com/8148364/100839754-b7a69180-34af-11eb-92de-cb9a1bd9256b.png)

**Comment by xiaosan666** [comment]
其他：文档是用 https://docsify.js.org/#/zh-cn/ 写的

**Comment by fuchengwei** [comment]
增加配置 不删除本地打包目录吗？

**Comment by xiaosan666** [comment]
是的，可以通过配置，不删除/dist目录

**Comment by yanxiaojun617** [comment]
看来作者比较忙，关闭了

**Comment by fuchengwei** [comment]
不好意思 这段时间比较忙 忘记了 现在已经添加好了 升级 1.2.4版本即可 增加了 isRemoveLocalFile 这个配置项
