### ISSUE TITLE
打包错误

### ISSUE THREAD

**Issue by lurenwu** [fuchengwei/deploy-cli-service#3]
? blue-ydb 项目是否部署到 开发环境? Yes
(1) npm run build
✖ 打包失败
✖ stdout maxBuffer length exceeded

**Comment by fuchengwei** [comment]
缓冲区大小不够，后面我修改一下，调大一些吧。

**Comment by lurenwu** [comment]
1

**Comment by fuchengwei** [comment]
这个问题已经修复了
