### ISSUE TITLE
ubuntu 20.04 ssh 连接异常

### ISSUE THREAD

**Issue by gogHeroDream** [fuchengwei/deploy-cli-service#31]
![错误内容](https://filessourcesk.open.com.cn/opensk/11/7/course/20210604/354A4F6F4DAE40558C702E3E61271A41.png)
第三步 ssh 连接 *** 然后：
✖ AssertionError [ERR_ASSERTION]: config.privateKey does not exist at given fs path
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

私钥文件权限给了777 也还是不行    ~/.ssh/id_rsa

**Comment by gogHeroDream** [comment]
是否支持 linux 系统呢？

**Comment by fuchengwei** [comment]
支持linux系统 你的私钥文件地址对吗

**Comment by gogHeroDream** [comment]
> 支持linux系统 你的私钥文件地址对吗

私钥地址对呀。~/.ssh/id_rsa  这个 ，能打开看到。

**Comment by gogHeroDream** [comment]
> 支持linux系统 你的私钥文件地址对吗
好吧 换成 全路径就好了  ~ 不行。
