### ISSUE TITLE
打包压缩后文件的日期是当前时间-8h

### ISSUE THREAD

**Issue by juststand2046** [fuchengwei/deploy-cli-service#33]
标题所述

**Comment by fuchengwei** [comment]
这说明你的服务器时间时区是不对的 你需要去调整你的服务器时间

**Comment by juststand2046** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by juststand2046** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 晚上6:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fuchengwei/deploy-cli-service] 打包压缩后文件的日期是当前时间-8h (Issue #33)





 
这说明你的服务器时间时区是不对的 你需要去调整你的服务器时间
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
