### ISSUE TITLE
(node:27864) UnhandledPromiseRejectionWarning: Error: ENOTEMPTY: directory not empty, rmdir 'G:\xxxxxx\xxx/dist'

### ISSUE THREAD

**Issue by MaybeQHL** [fuchengwei/deploy-cli-service#34]
![image](https://user-images.githubusercontent.com/34638673/150096640-f88e54f4-82e0-4b8c-9595-3e5b0e65a09c.png)

**Comment by fuchengwei** [comment]
每次都出现这个 还是偶尔？

**Comment by MaybeQHL** [comment]
每次都出现，服务器上的逻辑能正常执行，就是本地最后一步清除文件夹报了错，但是文件夹内容也清空了。

**Comment by MaybeQHL** [comment]
其实最后一步清除文件夹内容可以去除，因为打包后每次都会清除里面内容
