### ISSUE TITLE
备份文件在服务器上找不到

### ISSUE THREAD

**Issue by yadanchina** [fuchengwei/deploy-cli-service#35]
备份文件在服务器上找不到

**Comment by yadanchina** [comment]
webDir:/home/admin/web/dist
bakDir:/home/admin/web
这样备份文件就找不到
bakDir:/home/admin/web/backup
这样就能找到了

**Comment by fuchengwei** [comment]
bakDir和webDir不要放在同一个目录内 删除远程文件时 同名会删除掉
