### ISSUE TITLE
这个在ts 文件中怎么引用啊

### ISSUE THREAD

**Issue by Verdicts-ye** [fuchengwei/deploy-cli-service#37]
deploy.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename deploy.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\Users\Administrator\Desktop\work\jc-admin\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

如果将package.json的type 改成 commonjs 是可以用，但同时也就失去了 type 为module的tree-shaking优化。

**Comment by fuchengwei** [comment]
不支持 ts，读取的配置文件路径和文件名是固定的 deploy.config.js
