### ISSUE TITLE
服务器登录密码隐藏

### ISSUE THREAD

**Issue by yan01290129** [fuchengwei/deploy-cli-service#38]
团队项目生产部署，这个服务器登录密码能不能在运行时动态录入进去啊

**Comment by fuchengwei** [comment]
目前已经支持这种功能了
删除配置文件中的 password 字段即可

**Comment by fuchengwei** [comment]
目前已经支持这种功能了
删除配置文件中的 password 字段即可

**Comment by fuchengwei** [comment]
目前已经支持这种功能了
删除配置文件中的 password 字段即可
