### ISSUE TITLE
ssh 超时时间

### ISSUE THREAD

**Issue by ggboypro** [fuchengwei/deploy-cli-service#39]

**Comment by ggboypro** [comment]
链接海外的服务器经常超时，需要超时时间配置

**Comment by fuchengwei** [comment]
升级到最新 1.4.0 版本 配置中添加了 readyTimeout 配置
![image](https://user-images.githubusercontent.com/31444224/211963215-8504e816-255f-444f-a1a0-167fb68007a7.png)
