### ISSUE TITLE
希望 webDir 可以支持数组的配置

### ISSUE THREAD

**Issue by nmy0808** [fuchengwei/deploy-cli-service#47]
你好, 希望webDir这里可以放个数组, 有时候需要放服务器的两个位置, 但是部署的文件内容是一致的, 不想打包两次, 想打包一次分别放到服务器的两个位置
如:
    webDir: ["地址一", "地址二"]

谢谢作者!

**Comment by fuchengwei** [comment]
可以考虑使用集群部署配置
cluster: ['dev', 'dev']
这种方式来实现
