### ISSUE TITLE
关于压缩包文件时间问题

### ISSUE THREAD

**Issue by Locksmith-Mr** [fuchengwei/deploy-cli-service#48]
您使用的是zip包 , [node-zip-stream](https://github.com/archiverjs/node-zip-stream)

目前问题是, 如果不设置forceLocalTime, 则压缩包里的文件时间会有时区问题

建议您默认设置forceLocalTime为true,  或者开放给开发者自由配置
![QQ图片20231212132846](https://github.com/fuchengwei/deploy-cli-service/assets/29303710/c67263cd-24ca-42e8-b41a-3b35d0a3545b)

**Comment by fuchengwei** [comment]
已添加 forceLocalTime为true，发布了最新版。
