### ISSUE TITLE
不知道为啥最近出现这个错误

### ISSUE THREAD

**Issue by MaybeQHL** [fuchengwei/deploy-cli-service#49]
以前是正常的，更新到最新版本也这样。

![image](https://github.com/fuchengwei/deploy-cli-service/assets/34638673/4bb4f10f-26e7-4702-ac09-8bf15376fb13)

**Comment by fuchengwei** [comment]
看报错是说删除本地文件的时候的目录不是空的 打包后的目录是什么样子呢

**Comment by MaybeQHL** [comment]
![image](https://github.com/fuchengwei/deploy-cli-service/assets/34638673/34646be8-dc4d-4846-bcc3-88068e4671e4)
![image](https://github.com/fuchengwei/deploy-cli-service/assets/34638673/55b5f881-e68f-4c99-aab2-458c70c2f14b)
根目录有压缩包的残留没有删除，之前上传完后都是清除的。

**Comment by MaybeQHL** [comment]
dist目录里面也是空的。

**Comment by MaybeQHL** [comment]
不知道为啥又好了

**Comment by weiweiweigang** [comment]
很是神奇。我分别在两个项目中使用，一个项目中正常。另一个项目中也遇到你的这个问题，还没解决
