### ISSUE TITLE
请问支持windows2012服务器部署吗

### ISSUE THREAD

**Issue by congceng999** [fuchengwei/deploy-cli-service#6]
请问支持windows2012服务器部署吗？不是ssh连接的

**Comment by fuchengwei** [comment]
windows 服务器不支持的 现在只支持 ssh 连接

**Comment by cn1001wang** [comment]
window server 2019可以直接安装 OpenSSH。[Installation of OpenSSH For Windows Server 2019 and Windows 10](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)

2019之下的版本可以安装OpenSSH的应用请看[这篇文章](https://www.server-world.info/en/note?os=Windows_Server_2016&p=openssh)，遇到的问题请看[这个视频](https://www.youtube.com/watch?v=gUOEaZb0gW8&feature=youtu.be)
