### ISSUE TITLE
提个需求啊

### ISSUE THREAD

**Issue by nxboo** [fuchengwei/deploy-cli-service#8]
非常感谢 @fuchengwei 开发的这个工具

是否可以提几个需求？
1.布署可能会涉及多台服务器，能否支持多台服务器？
2.目前布署需要同时打包，是否可以不打包？
3.布署时需要备份线上版本，是否可以支持“布署前”和“布署后”在服务器上执行一条shell的功能？

**Comment by fuchengwei** [comment]
你的需求我会考虑 但我需要想一想如何在增加这些功能的同时，不影响之前的配置和使用

**Comment by nxboo** [comment]
> 你的需求我会考虑 但我需要想一想如何在增加这些功能的同时，不影响之前的配置和使用

感谢老大
1.布署可能会涉及多台服务器，能否支持多台服务器？
建议可以参考TypeOrm的配置方式，单个连接是个对像，多个连接是个数组 https://typeorm.io/#/multiple-connections

2.目前布署需要同时打包，是否可以不打包？
这个判断打包命令是否为空，应该就可以的

**Comment by jimdeng92** [comment]
@nxboo 如果你有不错的解决方案，建议可以拉一下作者的仓库贡献自己的代码。如果是不错的功能，我想作者会处理合并请求的。

**Comment by fuchengwei** [comment]
目前已支持集群部署与部署前不打包
