### ISSUE TITLE
1.1.0版本问题

### ISSUE THREAD

**Issue by zhuli2010** [fuchengwei/deploy-cli-service#9]
前天我用1.0.9版本OK，这个工具感觉非常不错，这里得先感谢一下作者。但是您这里升级得1.1.0版本，文件处理顺序令我惊呆了，我在云端所有得项目都没有了，发现你这边得远端文件处理顺序由先删除旧文件，再上传新文件改成了先上传新文件，上传成功再删除远端文件，oh my god！

**Comment by fuchengwei** [comment]
这应该不是这个问题导致的吧？
我只是调整了执行的步骤 保证在发布的时候 不会有很长的时间 项目不能访问，你先确定一下配置上传的目录是否正确，我不太理解所有项目没有是某个文件夹下的文件都删除了吗？
